In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv")

In [3]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [4]:
pd.__version__

'2.2.2'

In [7]:
df.shape[0]

2160

In [9]:
len(df['Brand'].unique())

27

In [10]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [12]:
df_dell_notebooks = df[df["Brand"] == "Dell"]

In [14]:
df_dell_notebooks["Final Price"].max()

np.float64(3936.0)

In [16]:
df["Screen"].median()

np.float64(15.6)

In [17]:
df.mode()['Screen']

0       15.6
1        NaN
2        NaN
3        NaN
4        NaN
        ... 
2155     NaN
2156     NaN
2157     NaN
2158     NaN
2159     NaN
Name: Screen, Length: 2160, dtype: float64

In [18]:
df['Screen'] = df['Screen'].fillna(15.6)

In [19]:
df["Screen"].median()

np.float64(15.6)

In [20]:
df_innjoo_notebooks = df[df["Brand"] == "Innjoo"]

In [21]:
df_innjoo_notebooks = df_innjoo_notebooks[['RAM', 'Storage', 'Screen']]

In [24]:
X = df_innjoo_notebooks.to_numpy()

In [25]:
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [28]:
import numpy as np

In [42]:
XTX = np.dot(X.T, X)

In [43]:
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [46]:
XTX_Inv = np.linalg.inv(XTX)

In [47]:
XTX_Inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [50]:
y = [1100, 1300, 800, 900, 1000, 1100]

In [52]:
w1 = np.dot(XTX_Inv, X.T)

In [53]:
w = np.dot(w1, y)

In [54]:
w

array([45.58076606,  0.42783519, 45.29127938])